# https://taskfile.dev

version: "3"

vars:
  BACKEND_DIRECTORY: /backend
  FRONTEND_DIRECTORY: /frontend
  # PROGRAM: ./backend/main.go

tasks:
  default:
    cmds:
      - task backend
      - task frontend
  backend:
    dir: "{{.BACKEND_DIRECTORY}}"
    cmds:
      - go run .
  add:
    cmds:
      - git add .
  frontend:
    dir: "{{.FRONTEND_DIRECTORY}}"
    cmds:
      - bun run dev
  air:
    dir: "{{.BACKEND_DIRECTORY}}"
    cmds:
      - air
